import * as React from "react";
const VillainDeco = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={500}
    height={500}
    viewBox="0 0 300 270"
    fill="none"
    {...props}
  >
    <text
      x={25}
      y={50}
      stroke="#1b1b1b"
      fill="#ff0099"
      fontSize={45}
      fontFamily="Dalfitra"
    >
      {"AGI"}
    </text>
    <text
      x={115}
      y={50}
      stroke="#1b1b1b"
      fill="#ff0099"
      fontSize={45}
      fontFamily="Dalfitra"
    >
      {"AGI"}
    </text>
    <text
      x={200}
      y={50}
      stroke="#1b1b1b"
      fill="#ff0099"
      fontSize={45}
      fontFamily="Dalfitra"
    >
      {"AGI"}
    </text>
    <text
      x={25}
      y={150}
      stroke="#1b1b1b"
      fill="#ff0099"
      fontSize={45}
      fontFamily="Dalfitra"
    >
      {"AGI"}
    </text>
    <text
      x={115}
      y={150}
      stroke="#1b1b1b"
      fill="#ff0099"
      fontSize={45}
      fontFamily="Dalfitra"
    >
      {"AGI"}
    </text>
    <text
      x={200}
      y={150}
      stroke="#1b1b1b"
      fill="#ff0099"
      fontSize={45}
      fontFamily="Dalfitra"
    >
      {"AGI"}
    </text>
    <text
      x={25}
      y={250}
      stroke="#1b1b1b"
      fill="#ff0099"
      fontSize={45}
      fontFamily="Dalfitra"
    >
      {"AGI"}
    </text>
    <text
      x={115}
      y={250}
      stroke="#1b1b1b"
      fill="#ff0099"
      fontSize={45}
      fontFamily="Dalfitra"
    >
      {"AGI"}
    </text>
    <text
      x={200}
      y={250}
      stroke="#1b1b1b"
      fill="#1b1b1b"
      fontSize={45}
      fontFamily="Dalfitra"
    >
      {"AGI"}
    </text>
  </svg>
);
export default VillainDeco;
